name: goe-pv-steuerung

services:
  goe-pv-steuerung:
    build: .
    restart: unless-stopped
    ports:
      - "2009:2009"
    volumes:
      # Persistierung der Konfiguration & SSL Zertifikate bei Container-Neustarts
      - ./config.json:/app/config.json
      - ./certs:/app/certs
    environment:
      - TZ=Europe/Vienna
      - PYTHONUNBUFFERED=1
